# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie1', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
